<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class ComplainList
 * @package App\Models
 * @property integer $id
 * @property integer $uid
 * @property integer $mina_id
 * @property integer $com_type
 * @property string $complain_remark
 * @property string $img1
 * @property string $img2
 * @property string $img3
 * @property integer $handle_type
 */
class ComplainList extends Model
{
    //
    public function save(array $options = [])
    {
        if($this->handle_type == 2){
            $result = parent::save($options);
            if($result){
                MinaInfo::where('id',$this->mina_id)->increment('complain_count');
            }
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
